sudo: false
language: python
python:
  - 3.5
  - 3.6
  - 3.7
matrix:
  include:
    - python: 3.7
      dist: xenial
install:
  # 针对每次的新环境安装相关依赖
  - pip install poetry
  - poetry install -vvv
script:
  # 普通的执行方式
  # - python -m unittest discover
  # coverage的执行方式
  - coverage run --source=test_api_job -m unittest discover
  - coverage report